// Contenu pédagogique original. Références officielles associées à chaque module.
export const sources = {
 start:['Prise en main de FortiOS 7.6.3','https://docs.fortinet.com/document/fortigate/7.6.3/administration-guide/954635/getting-started'],
 cli:['Référence pratique de diagnostic CLI 7.6','https://docs.fortinet.com/document/fortigate/7.6.0/cli-troubleshooting-cheat-sheet/420966/cli-troubleshooting-cheat-sheet'],
 interfaces:['Interfaces — FortiOS 7.6.3','https://docs.fortinet.com/document/fortigate/7.6.3/administration-guide/574723/interface-settings'],
 policy:['Policies — FortiOS 7.6.3','https://docs.fortinet.com/document/fortigate/7.6.3/administration-guide/118003/policies'],
 ngfw:['Modes NGFW — FortiOS 7.6.3','https://docs.fortinet.com/document/fortigate/7.6.3/administration-guide/243446/ngfw-policy'],
 security:['Profils de sécurité — FortiOS 7.6.3','https://docs.fortinet.com/document/fortigate/7.6.3/administration-guide/680955/security-profiles'],
 ipsec:['Configuration IPsec — FortiOS 7.6.3','https://docs.fortinet.com/document/fortigate/7.6.3/administration-guide/762500/general-ipsec-vpn-configuration'],
 sla:['Performance SLA — FortiOS 7.6','https://docs.fortinet.com/document/fortigate/7.6.0/administration-guide/584396/performance-sla'],
 debug:['Outil Debug Flow — FortiOS 7.6','https://docs.fortinet.com/document/fortigate/7.6.0/administration-guide/38044/using-the-debug-flow-tool'],
 method:['Méthodes de diagnostic — FortiOS 7.6.3','https://docs.fortinet.com/document/fortigate/7.6.3/administration-guide/321075/troubleshooting-methodologies'],
 ha:['Vérifier la synchronisation HA — FortiOS 7.6','https://docs.fortinet.com/document/fortigate/7.6.0/administration-guide/63913/check-ha-synchronization-status'],
 fabric:['Compatibilité Security Fabric — FortiOS 7.6.3','https://docs.fortinet.com/document/fortigate/7.6.3/fortios-release-notes/936594/fortinet-security-fabric-upgrade'],
 routes:['Routes statiques — FortiOS 7.6.3','https://docs.fortinet.com/document/fortigate/7.6.3/administration-guide/804259/static-routing'],
 prefixes:['Filtrage des préfixes — FortiOS 7.6.3','https://docs.fortinet.com/document/fortigate/7.6.3/administration-guide/3583/prefix-lists'],
 ldap:['Groupes Active Directory — FortiOS 7.6.3','https://docs.fortinet.com/document/fortigate/7.6.3/administration-guide/475491/tracking-users-in-each-active-directory-ldap-group'],
 fsso:['Connecteurs FSSO — FortiManager 7.6.3','https://docs.fortinet.com/document/fortimanager/7.6.3/administration-guide/303084/creating-fsso-connectors'],
 vdom:['Vue des VDOM — FortiOS 7.6.5','https://docs.fortinet.com/document/fortigate/7.6.5/administration-guide/597696/vdom-overview'],
 switch:['Guide FortiLink 7.6.3','https://docs.fortinet.com/document/fortiswitch/7.6.3/fortilink-guide'],
 tags:['Synchronisation des tags ZTNA — FortiOS 7.6.3','https://docs.fortinet.com/document/fortigate/7.6.3/administration-guide/335228/synchronizing-forticlient-ztna-tags'],
 ems:['Connexion sécurisée à EMS — FortiOS 7.6.3','https://docs.fortinet.com/document/fortigate/7.6.3/ztna-deployment/374384/connect-the-fortigate-to-ems'],
 snmp:['MIB SNMP — FortiOS 7.6.3','https://docs.fortinet.com/document/fortigate/7.6.3/administration-guide/608160/mib-files'],
 tls:['Inspection TLS — Guide de déploiement 7.6','https://docs.fortinet.com/document/fortigate/7.6.0/ngfw-web-security-deployment-guide/997305/deep-inspection'],
 dns:['DNS — FortiOS 7.6.3','https://docs.fortinet.com/document/fortigate/7.6.3/administration-guide/780581/dns'],
 remote:['Accès distant — FortiOS 7.6.3','https://docs.fortinet.com/document/fortigate/7.6.3/administration-guide/190553/remote-access'],
 migration:['Remplacement de SSL VPN tunnel en 7.6.3','https://docs.fortinet.com/document/fortigate/7.6.3/fortios-release-notes/173430/ssl-vpn-tunnel-mode-replaced-with-ipsec-vpn'],
 hardening:['Durcissement FortiOS 7.6','https://docs.fortinet.com/document/fortigate/7.6.0/best-practices/555436/hardening'],
 admin:['Comptes administrateurs — FortiOS 7.6.3','https://docs.fortinet.com/document/fortigate/7.6.3/administration-guide/14906'],
 analyzer:['Log View — FortiAnalyzer 7.6','https://docs.fortinet.com/document/fortianalyzer/7.6.0/administration-guide/584585/log-view-and-log-quota-management'],
 debugref:['Référence diagnose debug — FortiOS 7.6.6','https://docs.fortinet.com/document/fortigate/7.6.6/cli-reference/159376337/diagnose-debug'],
 haref:['Référence diagnose sys — FortiOS 7.6.4','https://docs.fortinet.com/document/fortigate/7.6.4/cli-reference/235530229/diagnose-sys'],
 manager:['Assistant d’installation FortiManager 7.6.3','https://docs.fortinet.com/document/fortimanager/7.6.3/administration-guide/952137/install-wizard'],
 preview:['Prévisualiser une installation FortiManager','https://docs.fortinet.com/document/fortimanager/7.6.3/upgrade-guide/768399/previewing-changes-for-a-policy-package-installation'],
 backup:['Sauvegarde — FortiOS 7.6.3','https://docs.fortinet.com/document/fortigate/7.6.3/administration-guide/324674/backing-up-the-configuration'],
 upgrade:['Informations de mise à jour 7.6.3','https://docs.fortinet.com/document/fortigate/7.6.3/fortios-release-notes/832438']
};
const q=(prompt,options,answer,explanation)=>({type:'choice',prompt,options,answer,explanation});
const t=(prompt,answers,explanation)=>({type:'text',prompt,answers,explanation});
export const courses = [
{
 id:1,slug:'fondamentaux-fortigate',title:'Comprendre FortiGate et le chemin d’un flux',level:'Fondations',minutes:40,
 objective:'Expliquer pourquoi un paquet passe ou est refusé, et relever le contexte d’un FortiGate.',prereq:'Savoir distinguer adresse IP, masque, passerelle et port TCP/UDP.',
 lessons:[
 ['Un pare-feu stateful','Un FortiGate conserve un état des connexions. Une nouvelle connexion doit satisfaire les décisions de routage et de sécurité ; les paquets suivants sont associés à une session. Une réponse appartenant à une session autorisée n’exige généralement pas une règle miroir. En revanche, une nouvelle connexion initiée dans le sens opposé doit être autorisée séparément. Une session existante explique parfois pourquoi une modification ne produit pas immédiatement le résultat attendu.'],
 ['Raisonner avec cinq informations','Avant de modifier une règle, note IP source, IP destination, protocole, port source et port destination, puis interfaces d’entrée et de sortie attendues. Une route indique où envoyer le paquet ; une policy décide si le flux est permis ; le NAT transforme une adresse. Ces fonctions sont distinctes. Le schéma entrée → route/policy → inspection/NAT → sortie est un repère de diagnostic simplifié, pas l’ordre interne universel de traitement.'],
 ['Séparer administration et transit','Une connexion HTTPS vers le FortiGate lui-même relève de son accès administratif et éventuellement des règles local-in. Une connexion traversant le FortiGate vers un serveur relève des policies de transit. Commence par relever modèle, version, mode et VDOM. Dans un laboratoire, garde un accès console et une sauvegarde afin de pouvoir revenir à un état connu. La version exacte compte davantage que la seule étiquette « 7.6 ».']
 ],gui:'Dashboard → Status pour l’état ; Network → Interfaces pour les adresses ; Policy & Objects → Firewall Policy pour les flux de transit.',
 cli:'get system status\nget system performance status\nget router info routing-table all',cliNote:'Lecture seule. Identifie le VDOM avant d’interpréter les routes. Une sortie de performance doit être comparée dans le temps.',
 example:'PC 10.10.10.10 → serveur 10.10.20.10:443 : le PC envoie à sa passerelle 10.10.10.1. Le FortiGate doit connaître le réseau du serveur et autoriser HTTPS entre les deux interfaces. Le serveur doit disposer d’un chemin retour.',
 exercise:['Dessine PC, passerelle et serveur, puis ajoute les interfaces du pare-feu.','Note le cinq-uplet d’un essai HTTPS et distingue-le d’un ping.','Relève version et route vers le serveur. Explique ce que ces informations prouvent et ce qu’elles ne prouvent pas.'],
 correction:'Une route correcte prouve un chemin de sortie potentiel, pas une autorisation. Un ping réussi valide ICMP pour ce trajet ; il ne valide ni TCP/443, ni le certificat, ni l’application.',pitfall:'Ajouter une règle WAN → LAN pour « autoriser les réponses » sans vérifier la session ouvre potentiellement de nouvelles connexions entrantes.',refs:['start','policy'],
 quiz:[q('Une route vers le serveur garantit-elle que HTTPS passe ?',['Oui, toujours','Non, il faut aussi une policy et les autres conditions du flux','Oui si le serveur répond au ping'],1,'Le routage et l’autorisation sont deux décisions différentes.'),q('Quel trafic relève de l’administration locale ?',['HTTPS vers l’adresse du FortiGate','HTTPS traversant le FortiGate vers un serveur','Un paquet vers une agence distante'],0,'La destination est ici le pare-feu lui-même.'),t('Quel objet mémorise l’état d’une connexion ?',['session','une session'],'La session relie les paquets d’une même connexion.')]
},
{
 id:2,slug:'interfaces-vlan',title:'Interfaces, VLAN et adressage',level:'Fondations',minutes:50,
 objective:'Construire un segment VLAN et distinguer une panne de niveau 2 d’une panne de routage.',prereq:'Module 1 ; notions de sous-réseau IPv4.',
 lessons:[['Un VLAN est un domaine de niveau 2','Le tag 802.1Q permet de transporter plusieurs réseaux logiques sur un lien. Le port d’un poste est généralement en accès non tagué dans un VLAN ; le lien vers le FortiGate transporte ce VLAN tagué. Le numéro du VLAN doit correspondre des deux côtés. Donner une adresse IP à une sous-interface ne corrige pas un trunk qui ne transporte pas le bon tag.'],['Passerelle et DHCP','Pour VLAN10, la passerelle peut être 10.10.10.1/24, avec une plage DHCP 10.10.10.100–150. Exclue les adresses statiques de cette plage. Un serveur DHCP local ou un relais vers un serveur central sont deux architectures distinctes. Le bail doit contenir masque, passerelle et DNS appropriés. Une adresse automatique de secours sur le poste signale souvent l’absence de réponse DHCP.'],['Valider couche par couche','Vérifie d’abord lien physique, appartenance VLAN et table MAC du switch. Contrôle ensuite bail, ARP vers la passerelle et accès IP local. Une route connectée apparaît si l’interface concernée est opérationnelle. Pour passer d’un VLAN à un autre, il faut encore une policy. Le masque incorrect d’un poste peut l’amener à chercher localement par ARP une destination qui devrait être routée.']],
 gui:'Network → Interfaces → Create New → Interface : type VLAN, interface parente, VLAN ID et adresse. Les options disponibles dépendent du modèle.',
 cli:'show system interface\nget system arp\nshow system dhcp server',cliNote:'Lecture seule ; la configuration affichée décrit les interfaces et serveurs DHCP. Elle ne garantit pas le transport du VLAN par le switch.',
 example:'Un poste en VLAN10 reçoit 10.10.10.120/24 et la passerelle 10.10.10.1. Si le trunk ne laisse passer que VLAN20, ses broadcasts DHCP ne rejoignent pas VLAN10 sur le FortiGate.',
 exercise:['Sur un laboratoire isolé, prépare VLAN10 et VLAN20 sur un switch et leurs passerelles sur le FortiGate.','Associe un port de test à VLAN10, configure une plage DHCP dédiée et renouvelle le bail.','Retire uniquement VLAN10 du trunk de test, observe l’échec, puis rétablis la valeur initiale.'],correction:'Le lien peut rester physiquement UP pendant la panne. L’absence d’échanges DHCP sur la sous-interface, alors que le poste les émet, oriente vers le transport VLAN. Après restauration, un bail et un accès à la passerelle valident le segment.',pitfall:'Confondre VLAN natif non tagué et VLAN tagué, ou réutiliser le même sous-réseau sur deux interfaces isolées.',refs:['interfaces'],
 quiz:[q('Le tag du trunk ne correspond pas à la sous-interface. Que vérifier en premier ?',['Le numéro de VLAN des deux côtés','Le profil antivirus','Le mot de passe VPN'],0,'Le transport de niveau 2 doit être cohérent avant le routage.'),t('Quel numéro de VLAN utilise le segment VLAN10 de cet exercice ?',['10','vlan10','vlan 10'],'Le segment pédagogique est associé au tag 10.'),q('Deux VLAN différents peuvent-ils communiquer automatiquement ?',['Oui, car ils partagent le câble','Non : routage et autorisation sont nécessaires','Seulement avec du NAT systématique'],1,'La séparation de niveau 2 ne disparaît pas avec un trunk.')]
},
{
 id:3,slug:'policies-nat',title:'Policies, SNAT et publication par VIP',level:'Fondations',minutes:55,
 objective:'Définir une règle minimale et expliquer les adresses avant et après traduction.',prereq:'Modules 1 et 2.',
 lessons:[['Lire une règle de haut en bas','Une policy associe interfaces, sources, destinations, services et horaires. L’ordre compte : une règle large placée avant une règle plus précise peut la masquer. Sans correspondance autorisée, le trafic est refusé. Nomme la règle avec son besoin métier et active une journalisation adaptée. Vérifie l’identifiant de la policy réellement utilisée dans les logs, pas seulement son nom dans la configuration.'],['SNAT en sortie','Un client privé a généralement besoin de SNAT pour sortir vers Internet. Avec traduction sur l’interface de sortie, plusieurs clients peuvent utiliser l’adresse de cette interface et des ports différents. Entre deux LAN routés, conserve les sources lorsque l’architecture le permet : le NAT n’est pas une condition générale du routage. En mode Central SNAT, la traduction se configure séparément des règles de sécurité.'],['DNAT et VIP','Une VIP associe une adresse ou un port exposé à une ressource interne. Elle ne remplace pas la règle autorisant le trafic vers cette ressource. Pour publier un service de test, documente adresse externe, adresse interne, ports et sources autorisées. Prévois le chemin retour et évite de mélanger le test depuis Internet avec un test interne vers l’adresse publique : le second peut demander un traitement différent.']],
 gui:'Policy & Objects → Addresses, Firewall Policy et Virtual IPs. Central SNAT apparaît selon le mode de configuration.',
 cli:'show firewall policy\nshow firewall vip\nshow firewall central-snat-map',cliNote:'Lecture seule. Ce cours utilise le mode NGFW profile-based ; le mode policy-based impose Central NAT et modifie le fonctionnement des menus.',
 example:'Autoriser VLAN10 → WAN pour DNS vers le résolveur prévu et HTTPS, avec SNAT. Pour une application DMZ, une VIP de laboratoire 192.0.2.10:443 → 10.10.20.10:443 nécessite aussi une policy WAN → DMZ.',
 exercise:['Écris la matrice source, destination, service, action et NAT pour ces deux besoins.','Crée les objets et règles dans le laboratoire, avec une source de test limitée.','Lance une nouvelle connexion puis relève policyid, source traduite et compteurs aller/retour.'],correction:'La sortie Internet doit montrer la traduction source attendue. Le flux publié doit viser le serveur interne après DNAT. Le simple fait de créer une VIP ne constitue pas une preuve d’ouverture du service.',pitfall:'Laisser une règle « all → all / ALL » en tête masque les erreurs et autorise davantage que le besoin.',refs:['policy','ngfw'],
 quiz:[q('Une VIP suffit-elle à publier un serveur ?',['Oui','Non, une policy correspondante reste nécessaire','Oui si le port est 443'],1,'La traduction et l’autorisation ont des rôles distincts.'),q('Quelle traduction modifie la source ?',['DNAT','SNAT','VLAN'],1,'SNAT signifie Source Network Address Translation.'),t('Quel champ du journal permet d’identifier la règle appliquée ?',['policyid','policy id'],'policyid est la référence de la règle utilisée.')]
},
{
 id:4,slug:'profils-securite',title:'Profils de sécurité et inspection',level:'Fondations',minutes:45,
 objective:'Choisir le bon profil et distinguer refus réseau, refus applicatif et problème TLS.',prereq:'Module 3.',
 lessons:[['Attribuer un rôle à chaque contrôle','Antivirus recherche du contenu malveillant ; IPS identifie des signatures d’attaque ; Web Filter traite des catégories et URL ; Application Control identifie des applications. Un service TCP/443 indique un port, pas une application fiable. En mode profile-based, les profils sont associés à une policy : créer un profil sans l’attacher ne protège pas les flux de cette règle.'],['Comprendre la visibilité','Un contrôle ne peut analyser que ce qu’il voit. Sur un trafic chiffré, l’inspection de certificat et l’inspection approfondie n’offrent pas la même visibilité. L’inspection approfondie déchiffre puis rechiffre ; les postes doivent faire confiance à l’autorité utilisée. Le choix flow/proxy, les licences et les capacités matérielles influencent les fonctions réellement disponibles. Documente ces prérequis avant le test.'],['Déployer avec preuves','Pars d’une application et d’une règle de test limitées. Observe d’abord les journaux, vérifie le profil effectivement appliqué, puis ajuste le comportement. Une erreur de catégorie, une signature IPS et un certificat non approuvé ne se résolvent pas de la même manière. Une exception doit préciser objet, justification, propriétaire et date de revue ; une désactivation globale détruit la preuve et élargit le risque.']],
 gui:'Security Profiles pour créer les profils ; Policy & Objects → Firewall Policy pour les appliquer ; Log & Report pour distinguer trafic et événements de sécurité.',
 cli:'show firewall policy\nshow antivirus profile\nshow ips sensor\nshow webfilter profile',cliNote:'Lecture seule. Compare les noms référencés dans la policy à ceux des profils réellement configurés.',
 example:'Une connexion HTTPS est acceptée au niveau réseau mais un événement Web Filter bloque la catégorie du site. Changer la route ne corrigera pas ce refus de contenu.',
 exercise:['Choisis une application de test interne et consigne son fonctionnement de référence.','Applique un seul profil à la règle de test puis génère un trafic bénin contrôlé.','Relève action, profil, policyid et horaire. Compare avec la référence avant de modifier un second contrôle.'],correction:'Un test exploitable associe un événement à la même session et au même instant. « Le site ne marche plus » ne distingue pas réseau, TLS et filtrage ; le journal du moteur donne la catégorie de cause.',pitfall:'Confondre une policy ACCEPT avec la garantie que tous les contrôles de sécurité laisseront passer le contenu.',refs:['security','tls'],
 quiz:[q('Un port 443 prouve-t-il l’identité d’une application ?',['Oui','Non','Uniquement sur un VLAN'],1,'Un port de transport ne suffit pas à identifier l’application.'),q('Créer un profil sans l’appliquer à une règle protège-t-il son trafic ?',['Oui','Non','Seulement après redémarrage'],1,'Le profil doit être associé au flux traité.'),t('Quel profil traite les catégories de sites web ?',['web filter','webfilter','filtrage web'],'Le filtrage web traite notamment les catégories et URL.')]
},
{
 id:5,slug:'vpn-sdwan',title:'VPN IPsec et choix de chemin SD-WAN',level:'Avancé',minutes:70,
 objective:'Diagnostiquer un tunnel établi sans trafic et interpréter une mesure de qualité WAN.',prereq:'Modules 2 et 3 ; deux FortiGate de laboratoire pour la pratique IPsec.',
 lessons:[['Séparer négociation et transport','IKE négocie les paramètres et l’authentification ; les associations IPsec protègent ensuite le trafic. Les sélecteurs définissent les réseaux concernés. Un tunnel UP ne prouve ni route vers le LAN distant, ni policy LAN → tunnel, ni chemin retour. Pour un tunnel route-based, raisonne avec une interface virtuelle, les routes correspondantes et les règles des deux sites.'],['Construire une interconnexion','Prends 10.10.10.0/24 au siège et 10.20.10.0/24 à l’agence. Les deux côtés doivent s’accorder sur IKE, authentification, propositions et sélecteurs. Utilise un secret de laboratoire propre à cet exercice ou des certificats adaptés. Pour cette interconnexion privée, évite le SNAT sauf besoin explicite. Une mauvaise traduction peut rendre le trafic incompatible avec les sélecteurs ou masquer sa source réelle.'],['Mesurer avant de choisir','SD-WAN regroupe des liens et choisit un chemin selon des règles et leur stratégie. Un SLA mesure latence, gigue et perte ; un lien physiquement UP peut être inutilisable. La cible de mesure doit représenter le service à atteindre. Définis les seuils et le retour au lien préféré. Le comportement des sessions déjà établies ne se déduit pas simplement de celui d’une nouvelle connexion.']],
 gui:'VPN → IPsec Tunnels ; Network → Static Routes ; Network → SD-WAN pour membres, règles et Performance SLAs.',
 cli:'get vpn ipsec tunnel summary\ndiagnose vpn tunnel list\ndiagnose sys sdwan health-check',cliNote:'Diagnostics de lecture. Compare compteurs avant et après un essai ciblé, sans conclure à partir d’un total historique.',
 example:'Le tunnel siège/agence est UP, mais les compteurs d’émission restent stables pendant le test. Vérifie d’abord que la route envoie réellement 10.20.10.10 vers le tunnel et que la policy correspond au flux.',
 exercise:['Crée un IPsec route-based entre les deux LAN de laboratoire et autorise un service précis.','Observe les compteurs en testant depuis un poste, puis retire la route de test et constate la différence.','Sur deux accès simulés, configure un SLA, dégrade un lien et relève le chemin choisi pour une nouvelle connexion.'],correction:'Un tunnel fonctionnel transporte des paquets dans les deux sens. Un SLA hors seuil explique une sélection SD-WAN seulement si la règle concernée utilise ce SLA et si un autre chemin est éligible.',pitfall:'Tester uniquement avec un ping émis par le FortiGate : sa source et son traitement peuvent différer du trafic d’un poste.',refs:['ipsec','sla'],
 quiz:[q('Un tunnel UP mais sans trafic prouve quoi ?',['L’application fonctionne','La négociation est établie, le chemin de données reste à vérifier','La route retour existe'],1,'Le contrôle IPsec et les données sont distincts.'),t('Quel indicateur mesure la variation de latence ?',['gigue','jitter','la gigue'],'La gigue traduit la variabilité du délai.'),q('Quel test valide le besoin d’un utilisateur ?',['Un essai depuis son segment vers le service cible','Le seul ping du FortiGate vers sa propre interface','La présence du nom du tunnel'],0,'Le test doit représenter le flux réel.')]
},
{
 id:6,slug:'logs-diagnostic',title:'Logs, sessions, sniffer et Debug Flow',level:'Avancé',minutes:60,
 objective:'Localiser une rupture dans un flux avec une preuve limitée et reproductible.',prereq:'Modules 1 à 5.',
 lessons:[['Commencer par les journaux','Fixe un horodatage et un flux précis, puis filtre les logs par source et destination. Relève action, policyid, interfaces et octets aller/retour. L’absence de log n’est pas une preuve de passage : la journalisation peut être désactivée ou l’événement non encore émis. Une capture répond à « où passent les paquets ? » ; Debug Flow explique certaines décisions internes.'],['Capturer sans tout collecter','Un filtre host réduit l’observation à un poste ; ajoute un port ou un protocole si nécessaire. Le niveau de verbosité et le nombre de paquets doivent être bornés. Compare interface d’entrée, interface de sortie et réponse. SYN répétés sans SYN-ACK orientent vers une rupture d’acheminement, un filtrage ou un serveur muet, mais n’identifient pas seuls le responsable.'],['Arrêter proprement le diagnostic','Filtre avant d’activer un debug, limite le nombre de traces puis désactive et réinitialise après le test. Certaines sessions accélérées matériellement n’apparaissent pas entièrement dans les outils logiciels. Commence par une nouvelle connexion contrôlée. Modifier l’offload ou vider des sessions peut perturber les usages ; ce n’est pas une première étape sur une production.']],
 gui:'Log & Report → Forward Traffic ; Network → Diagnostics → Debug Flow selon la version et les fonctions visibles.',
 cli:"diagnose sniffer packet any 'host 10.10.10.10 and port 443' 4 20 l\n\ndiagnose debug reset\ndiagnose debug flow filter addr 10.10.10.10\ndiagnose debug flow show function-name enable\ndiagnose debug flow trace start 20\ndiagnose debug enable\n\n# Après le test :\ndiagnose debug disable\ndiagnose debug flow trace stop\ndiagnose debug reset",cliNote:'À exécuter sur le laboratoire, en coordonnant tout debug déjà actif. Arrêter même si aucune ligne n’apparaît. Ctrl+C interrompt une capture en cours.',
 example:'Le sniffer voit le SYN entrer sur VLAN10 et sortir vers la DMZ, mais aucune réponse n’entre depuis la DMZ. La recherche se poursuit côté serveur, passerelle de retour ou réseau DMZ ; ouvrir toutes les policies du LAN n’est pas justifié.',
 exercise:['Définis un essai TCP/443 unique avec heure et adresses.','Capture 20 paquets au maximum et classe entrée, sortie, retour.','Active un Debug Flow ciblé pour une nouvelle tentative, puis exécute les commandes d’arrêt. Rédige une conclusion limitée aux preuves.'],correction:'« Le SYN quitte le FortiGate, aucun retour observé pendant 10 secondes » est une conclusion vérifiable. « Le serveur est mort » dépasse la preuve : un filtre ou une route retour peut aussi expliquer le silence.',pitfall:'Une capture vide peut venir du filtre, du VDOM, du moment du test ou de l’accélération, pas seulement de l’absence de trafic.',refs:['debug','method','cli'],
 quiz:[q('Aucun log est visible. Peut-on conclure que le flux passe ?',['Oui','Non','Oui si la policy existe'],1,'La configuration et le moment de journalisation doivent être vérifiés.'),t('Quelle commande désactive la sortie de debug ?',['diagnose debug disable','diag debug disable'],'Désactive le debug, puis arrête la trace et réinitialise les filtres.'),q('Un SYN sort sans réponse. Quelle conclusion est prouvée ?',['Le serveur est éteint','Aucun retour n’a été observé pendant la capture','Le certificat est invalide'],1,'La capture localise une absence sans identifier automatiquement sa cause.')]
},
{
 id:7,slug:'ha',title:'Haute disponibilité et synchronisation',level:'Avancé',minutes:50,
 objective:'Évaluer l’état d’un cluster et préparer un test de bascule contrôlé.',prereq:'Module 6 ; deux équipements compatibles pour les manipulations.',
 lessons:[['Disponibilité n’est pas sauvegarde','Un cluster actif/passif réduit l’interruption lors de certaines défaillances. Il ne protège pas automatiquement d’une mauvaise configuration propagée aux membres. Distingue état des membres, heartbeat, configuration synchronisée et reprise de sessions. Deux pare-feu dont les liens WAN dépendent du même équipement amont conservent ce point de panne commun.'],['Lire la synchronisation','Le tableau HA et la commande de statut indiquent les membres et leur état. Une divergence de checksum doit être reliée aux tables concernées et à la chronologie des changements. Compare version, connectivité heartbeat et contexte avant toute action. Ne force pas une synchronisation à l’aveugle : il faut savoir quelle configuration doit être conservée.'],['Tester une panne définie','Prépare un flux continu et une nouvelle connexion régulière. Définis quel événement est simulé, combien d’interruption est acceptable et comment revenir à l’état initial. Certaines sessions peuvent ne pas être reprises selon protocole et options. Mesure les pertes réellement constatées plutôt que de promettre une bascule totalement transparente. Vérifie ensuite la stabilité et la resynchronisation.']],
 gui:'System → HA et widget HA Status du Dashboard.',cli:'get system ha status\ndiagnose sys ha checksum cluster',cliNote:'Lecture seule. Les différences doivent être interprétées par table ; tous les paramètres locaux aux membres ne sont pas destinés à être identiques.',
 example:'Le primaire est sain mais le secondaire est hors synchronisation. Une bascule immédiate pourrait appliquer une configuration différente : le service semble disponible, mais la redondance n’est pas validée.',
 exercise:['Consigne les numéros de série, versions et rôles des deux membres de laboratoire.','Vérifie l’état synchronisé, lance un flux et simule une seule panne prévue au plan.','Mesure interruption et rétablissement ; restaure le lien et observe la stabilité du cluster.'],correction:'Le rapport doit distinguer panne détectée, changement de rôle, continuité des nouvelles connexions et reprise des anciennes sessions. Termine par une preuve de synchronisation et de fonctionnement.',pitfall:'Confondre heartbeat sain avec santé complète du service applicatif, ou tester plusieurs pannes en même temps.',refs:['ha','haref'],
 quiz:[q('Le HA remplace-t-il une sauvegarde ?',['Oui','Non','Seulement en actif/passif'],1,'Une erreur de configuration peut être propagée aux deux membres.'),q('Avant de forcer une synchronisation, que faut-il déterminer ?',['La configuration de référence à conserver','La couleur des interfaces','Le nombre de règles uniquement'],0,'Il faut éviter de propager le mauvais état.'),t('Quel canal permet notamment aux membres de se surveiller ?',['heartbeat','le heartbeat'],'Le heartbeat participe à la surveillance et à la coordination HA.')]
}
];
courses.push(
{
 id:8,slug:'ecosysteme',title:'Comprendre l’écosystème Fortinet',level:'Avancé',minutes:35,
 objective:'Choisir le composant adapté à un besoin et tracer ses dépendances.',prereq:'Modules 1 et 4.',
 lessons:[['Attribuer les responsabilités','FortiGate applique les décisions réseau et sécurité. FortiManager centralise la configuration ; FortiAnalyzer centralise l’analyse des journaux. FortiSwitch et FortiAP apportent l’accès filaire et Wi-Fi. FortiClient EMS administre les terminaux et leur posture. FortiGuard fournit différents services et renseignements de sécurité, selon les souscriptions. Ces rôles ne sont pas interchangeables : un outil de logs n’est pas un substitut au pare-feu.'],['Dessiner les dépendances','Pour chaque échange, note initiateur, destination, authentification, flux requis et effet d’une interruption. Un poste peut conserver un accès réseau alors que ses données de posture ne sont plus à jour. Une règle peut fonctionner pendant que ses logs ne rejoignent plus le collecteur. Le diagnostic doit donc distinguer plan de données, administration et télémétrie.'],['Valider la compatibilité','Avant d’intégrer ou mettre à jour un produit, vérifie les versions compatibles dans les guides correspondants et la matrice Security Fabric. Une même numérotation de version ne prouve pas une compatibilité complète. Prévois DNS, heure, certificats et droits d’administration. Procède sur un périmètre pilote avant de généraliser les connecteurs.']],
 gui:'Security Fabric → Physical Topology et Fabric Connectors ; les menus varient avec les produits connectés et les fonctions activées.',
 cli:'get system status\nshow system central-management\nshow log fortianalyzer setting',cliNote:'Ces commandes inventorient version et destinations de gestion/logs ; elles ne remplacent pas les tests de connectivité et d’autorisation des services.',
 example:'Trois agences doivent appliquer un même standard et conserver leurs événements. FortiManager répond au besoin de déploiement cohérent ; FortiAnalyzer répond au besoin d’analyse centralisée. Les deux flux se testent séparément.',
 exercise:['Dessine un siège et deux agences ; place pare-feu, switches, points d’accès et terminaux.','Affecte un composant au déploiement de règles, à la rétention de logs et au contrôle de posture.','Pour chaque lien de gestion, indique comment vérifier sa santé et qui reçoit une alerte en cas de panne.'],correction:'Une architecture exploitable identifie pour chaque service une source de vérité, une dépendance et un responsable. La perte du collecteur de logs doit être signalée même si les utilisateurs accèdent toujours à leurs applications.',pitfall:'Déclarer la Fabric opérationnelle parce que les icônes sont visibles, sans vérifier les échanges et la compatibilité.',refs:['fabric','start'],
 quiz:[q('Quel produit centralise principalement la configuration ?',['FortiAnalyzer','FortiManager','FortiAP'],1,'FortiManager sert à la gestion et au déploiement centralisés.'),t('Quel produit est associé à l’analyse centralisée des logs ?',['fortianalyzer','forti analyzer'],'FortiAnalyzer centralise les journaux et leur analyse.'),q('Des versions portant le même numéro sont-elles nécessairement compatibles ?',['Oui','Non, il faut vérifier la matrice','Oui si elles sont récentes'],1,'La compatibilité dépend des produits, builds et fonctions.')]
},
{
 id:9,slug:'routage-dynamique',title:'Routes statiques, OSPF et BGP',level:'Avancé',minutes:65,
 objective:'Distinguer voisinage, annonce et route installée ; éviter une fuite de préfixes.',prereq:'Modules 2, 3 et 5 ; bases des masques CIDR.',
 lessons:[['Choisir une route','Pour une destination donnée, une route plus spécifique prime sur une route moins spécifique. Pour des candidats comparables vers un même préfixe, distance administrative et critères du protocole interviennent. OSPF calcule des chemins au sein d’un domaine ; BGP échange des préfixes avec des voisins et applique une politique de sélection. Une route apprise ne garantit pas une policy autorisant le trafic.'],['Trois niveaux de validation','Le voisinage doit être établi, le préfixe doit être reçu et accepté, puis une route doit être installée et son prochain saut joignable. Un voisin BGP Established peut ne transmettre aucun préfixe utile. Un voisin OSPF présent ne prouve pas que le réseau distant est annoncé. Vérifie aussi le retour : les deux extrémités doivent savoir joindre les réseaux sources.'],['Filtrer ce qui est annoncé','Définis une liste des préfixes attendus et une politique d’import/export. Une prefix-list peut limiter réseau et longueurs de masque ; une route-map associe des conditions à des actions. N’active pas une redistribution générale sans inventorier ses effets. Dans un laboratoire à deux sites, commencer par annoncer un seul LAN rend les écarts visibles.']],
 gui:'Network → Static Routes ; paramètres OSPF/BGP selon Feature Visibility ; Dashboard → Network → Static & Dynamic Routing pour les routes et voisins.',
 cli:'get router info routing-table all\nget router info ospf neighbor\nget router info bgp summary',cliNote:'Lecture seule. Les commandes décrivent des états distincts : ne déduis pas la présence d’un préfixe du seul résumé des voisins.',
 example:'10.20.10.10 correspond à 10.20.10.0/24 et à 0.0.0.0/0 : la route /24 est la plus spécifique. Si elle disparaît, le trafic peut partir vers la route par défaut et quitter le chemin attendu.',
 exercise:['Commence par deux LAN reliés avec des routes statiques puis relève le fonctionnement.','Dans un laboratoire de routage, établis OSPF ou BGP et annonce seulement le LAN distant prévu.','Applique un filtre excluant ce préfixe ; observe que le voisinage peut rester actif malgré la disparition de la route. Rétablis le filtre.'],correction:'Le rapport doit montrer état du voisin, préfixe reçu/filtré et table de routage finale. La suppression de la route sans chute du voisin prouve la séparation entre session de contrôle et information utile.',pitfall:'Redistribuer routes connectées et route par défaut vers tous les voisins sans politique explicite.',refs:['routes','prefixes'],
 quiz:[q('Quelle route est la plus spécifique pour 10.20.10.10 ?',['0.0.0.0/0','10.20.0.0/16','10.20.10.0/24'],2,'/24 couvre un ensemble plus restreint que /16 et /0.'),q('BGP Established garantit-il une route utilisable ?',['Oui','Non','Oui si le ping fonctionne'],1,'Un voisin établi peut ne fournir aucun préfixe accepté.'),t('Quel outil filtre des routes par préfixe et longueur de masque ?',['prefix-list','prefix list','prefix lists'],'Une prefix-list peut imposer des contraintes de masque ge/le.')]
},
{
 id:10,slug:'identite-fsso',title:'Active Directory, LDAP, RADIUS et FSSO',level:'Avancé',minutes:55,
 objective:'Séparer vérification d’identité, groupes et association utilisateur/IP.',prereq:'Module 3 ; un annuaire de laboratoire pour la pratique.',
 lessons:[['Authentifier puis autoriser','L’authentification vérifie une identité ; l’autorisation détermine ce que cette identité peut faire. LDAP interroge un annuaire et peut servir à vérifier un utilisateur et ses groupes. RADIUS permet de déléguer des décisions d’authentification à un serveur. Un mot de passe accepté n’implique pas que l’utilisateur appartient au groupe requis par la policy.'],['Comprendre FSSO','FSSO transmet des informations de connexion pour associer des utilisateurs et groupes à des adresses IP. La fraîcheur de cette association compte : changement de bail, déconnexion ou poste partagé peuvent compliquer l’interprétation. Compare le poste réel, son IP et l’identité visible sur le FortiGate. Un test LDAP réussi ne prouve pas à lui seul que les événements FSSO arrivent correctement.'],['Décomposer un échec','Contrôle résolution DNS, heure, transport sécurisé et compte de service, puis recherche de l’utilisateur et correspondance des groupes. Vérifie ensuite l’IP associée et l’ordre des policies. Utilise un compte de service aux droits nécessaires et un annuaire de test ; évite les mots de passe dans des captures, scripts partagés ou historiques.']],
 gui:'User & Authentication → LDAP Servers, RADIUS Servers et User Groups ; Security Fabric → Fabric Connectors pour les connecteurs d’identité selon version.',
 cli:'show user ldap\nshow user group\ndiagnose debug authd fsso list',cliNote:'Les sorties peuvent contenir des noms de comptes, groupes ou détails sensibles. Conserve-les dans le dossier technique autorisé, pas dans un dépôt public.',
 example:'Alice appartient au groupe Support, mais le FortiGate associe son IP à une session plus ancienne. Changer son mot de passe ne corrige pas nécessairement l’association FSSO obsolète.',
 exercise:['Avec deux comptes de test appartenant à des groupes différents, documente les droits attendus.','Compare authentification, groupe remonté et association IP/utilisateur.','Effectue une nouvelle connexion depuis chaque poste puis retrouve la policy utilisée.'],correction:'La preuve complète est : compte reconnu, groupe attendu, association IP actuelle et policy correspondante. Un seul bouton « Test successful » dans LDAP ne couvre pas toute cette chaîne.',pitfall:'Placer une règle générale avant la règle par groupe, puis attribuer à FSSO le fait que celle-ci ne soit jamais utilisée.',refs:['ldap','fsso','debugref'],
 quiz:[q('LDAP fonctionne mais la mauvaise identité apparaît. Que vérifier ?',['L’association IP/utilisateur et sa fraîcheur','Le VLAN du serveur web uniquement','Le nombre de policies'],0,'FSSO transporte une association qui peut différer du résultat d’un test LDAP.'),t('Quel protocole d’annuaire est abordé ici ?',['ldap','ldaps'],'LDAP interroge l’annuaire ; LDAPS protège son transport par TLS.'),q('Authentifié signifie-t-il autorisé à toutes les ressources ?',['Oui','Non','Oui dans un domaine AD'],1,'Les permissions et groupes restent à évaluer.')]
},
{
 id:11,slug:'vdom',title:'VDOM et séparation des contextes',level:'Avancé',minutes:45,
 objective:'Diagnostiquer dans le bon domaine et expliquer les échanges entre VDOM.',prereq:'Modules 3 et 9.',
 lessons:[['Une séparation logique','Les VDOM divisent un FortiGate en contextes disposant de configurations réseau et de sécurité distinctes. Certaines ressources et certains paramètres restent globaux. Le nombre disponible et les fonctions dépendent du modèle et des licences. Une séparation logique n’annule pas les ressources physiques communes ni les risques d’une panne de l’équipement.'],['Le contexte change la lecture','La même adresse peut exister dans des contextes isolés. Avant de lire une route, une policy ou une session, identifie le VDOM concerné. Un administrateur limité peut ne pas voir les autres domaines. Le domaine de gestion et les services générés par l’équipement doivent être compris séparément des flux de transit.'],['Relier sans supprimer la séparation','Un lien inter-VDOM crée un chemin entre domaines ; il ne donne pas une autorisation universelle. Chaque côté doit avoir adressage, routes et policies adaptés. Dessine le parcours complet : interface utilisateur, premier domaine, lien inter-VDOM, second domaine puis sortie. Un oubli sur l’un des domaines suffit à bloquer le trajet.']],
 gui:'Sélecteur de VDOM, contexte Global et vues propres à chaque VDOM. L’activation multi-VDOM dépend du modèle et doit être préparée.',
 cli:'get system status\n\n# Sur un laboratoire où le VDOM LAB existe déjà :\nconfig vdom\n    edit LAB\n        get router info routing-table all\n    end',cliNote:'Remplace LAB par un VDOM existant confirmé. Ne change pas le mode VDOM d’un équipement en production pour suivre cet exercice.',
 example:'Une route par défaut existe dans root mais pas dans le VDOM des utilisateurs. Elle ne suffit pas à assurer leur sortie Internet.',
 exercise:['Sur un laboratoire déjà configuré en multi-VDOM, relève les interfaces affectées à chaque domaine.','Trace un échange inter-VDOM avec les routes et policies nécessaires des deux côtés.','Consulte la table de routage dans chaque contexte et explique les différences.'],correction:'Le flux doit être autorisé sur toutes les portions où une décision de sécurité s’applique. Une route visible dans un domaine ne doit pas être supposée présente dans l’autre.',pitfall:'Lancer un diagnostic dans root alors que le trafic traverse LAB, puis conclure que le FortiGate ne voit aucun paquet.',refs:['vdom'],
 quiz:[q('Une route de root est-elle automatiquement une route de tous les VDOM ?',['Oui','Non','Seulement la route par défaut'],1,'Chaque contexte possède sa configuration de routage.'),t('Quel contexte porte notamment les paramètres communs aux VDOM ?',['global','le contexte global'],'Les paramètres communs sont gérés dans le contexte Global.'),q('Un lien inter-VDOM remplace-t-il les policies ?',['Oui','Non','Oui si ses interfaces sont UP'],1,'Il crée une connectivité, pas une autorisation générale.')]
},
{
 id:12,slug:'fortiswitch-fortiap',title:'FortiSwitch, FortiLink et FortiAP',level:'Production',minutes:55,
 objective:'Suivre un terminal du port ou SSID jusqu’à sa passerelle.',prereq:'Module 2 ; matériel ou environnement d’accès adapté.',
 lessons:[['Gestion et trafic utilisateur','FortiLink permet la gestion de FortiSwitch depuis le FortiGate. Distingue découverte, autorisation et transport des VLAN utilisateurs. Un switch reconnu dans la console ne garantit pas que le port du poste appartient au bon VLAN. Documente les uplinks et la topologie avant de modifier les liens, afin d’éviter boucles ou perte de gestion.'],['Wi-Fi : plusieurs étapes','Un terminal doit voir le SSID, s’authentifier, obtenir une adresse puis atteindre son service. Une association radio réussie ne prouve pas que DHCP fonctionne. Le mode de transport du SSID, tunnel ou bridge selon l’architecture, détermine où le trafic est remis au réseau. Le VLAN réellement utilisé et la policy de sortie doivent correspondre au besoin.'],['Observer le client, pas seulement l’équipement','Relève MAC du terminal, port ou AP, SSID, VLAN, adresse et heure de l’essai. Vérifie l’état radio et les erreurs de liaison, puis la chaîne DHCP/DNS. Les problèmes de portée ou d’interférence se distinguent des refus de pare-feu : un signal faible et un événement de policy ne représentent pas la même panne.']],
 gui:'WiFi & Switch Controller pour les switches, FortiAP, SSID et ports gérés. Les libellés exacts suivent le modèle et la version du contrôleur.',
 cli:'show system interface\nshow switch-controller managed-switch\nshow wireless-controller vap',cliNote:'Inventaire de lecture ; les sections peuvent être absentes si le produit ou la fonction ne sont pas pris en charge.',
 example:'Un client est connecté au SSID Invités mais reçoit une adresse du VLAN interne. Le premier contrôle porte sur l’association SSID/VLAN et le chemin bridge/tunnel, avant d’élargir une policy.',
 exercise:['Dresse une fiche de chemin pour un client filaire puis un client Wi-Fi.','Compare segment attendu, bail reçu et policy de sortie.','Sur un port ou SSID de test, corrige une affectation de VLAN erronée, puis renouvelle le bail et reteste.'],correction:'La validation doit relier terminal, port/SSID, VLAN et passerelle. Un équipement « Online » ne valide pas cette chaîne. Le client doit recevoir le bon sous-réseau et rester limité aux services prévus.',pitfall:'Réinitialiser tout un switch ou point d’accès pour une erreur limitée à un port ou à un SSID.',refs:['switch','fabric'],
 quiz:[q('Un client associé à un SSID a-t-il forcément une adresse valide ?',['Oui','Non','Oui si le signal est fort'],1,'L’association radio précède les échanges DHCP.'),t('Quel mécanisme gère les FortiSwitch depuis le FortiGate ?',['fortilink','forti link'],'FortiLink est le mécanisme d’intégration des switches.'),q('Quel relevé localise un client ?',['MAC, port/AP, VLAN et IP','Seulement le nom du pare-feu','Uniquement sa catégorie web'],0,'Ces éléments reconstituent son chemin d’accès.')]
},
{
 id:13,slug:'ems-ztna',title:'FortiClient EMS, posture et ZTNA',level:'Production',minutes:55,
 objective:'Expliquer une décision d’accès combinant utilisateur, terminal et posture.',prereq:'Modules 10 et 15 conseillé pour les certificats ; EMS et licences adaptés pour la pratique.',
 lessons:[['La posture est une information','EMS reçoit des données des terminaux et applique des règles de tags : appartenance à un domaine, état de sécurité ou autres critères disponibles. FortiGate synchronise ces informations via un connecteur. Un tag attendu mais absent exige de vérifier la règle EMS, le dernier contact du terminal et la synchronisation. L’IP seule ne résume pas l’identité et l’état du terminal.'],['Comprendre les contrôles possibles','Les tags peuvent participer à des règles de sécurité. Une passerelle applicative ZTNA peut contrôler l’accès à une application avec identité, certificat du terminal et posture. L’utilisation de tags dans une firewall policy n’est pas à elle seule identique à une passerelle ZTNA complète. Les capacités diffèrent selon plateforme, mémoire, version et produit client.'],['Valider le cycle complet','Vérifie le certificat du serveur EMS, l’autorisation du FortiGate côté EMS et la présence des tags. Teste ensuite un terminal conforme et un terminal volontairement non conforme dans le laboratoire. Mesure le délai de changement observé. Une posture n’est pas nécessairement recalculée instantanément : le cycle de télémétrie et de synchronisation doit être pris en compte.']],
 gui:'Security Fabric → Fabric Connectors → FortiClient EMS ; Policy & Objects → ZTNA pour les tags et règles disponibles.',
 cli:'show endpoint-control fctems\ndiagnose firewall dynamic list',cliNote:'Lecture seule. Compare les adresses résolues par les objets dynamiques avec le terminal réellement testé.',
 example:'Un poste a le bon utilisateur mais manque le tag « conforme ». Autoriser le groupe AD seul contournerait le contrôle de posture prévu ; il faut comprendre pourquoi le tag n’est pas présent.',
 exercise:['Définis une règle de conformité observable dans EMS sur un groupe pilote.','Vérifie sa synchronisation et limite une application de test au groupe et à la posture attendus.','Modifie le critère sur le terminal de laboratoire, observe le résultat puis restaure sa conformité.'],correction:'La preuve relie état terminal, tag EMS, objet synchronisé et décision d’accès. Une simple capture d’un tag dans EMS ne prouve pas son utilisation effective par le FortiGate.',pitfall:'Traiter une information de posture ancienne comme une preuve actuelle, ou confondre la confiance TLS avec l’autorisation de l’équipement.',refs:['tags','ems'],
 quiz:[q('Un tag présent dans EMS prouve-t-il qu’il est appliqué au flux ?',['Oui','Non, synchronisation et règle restent à vérifier','Oui après un ping'],1,'Il faut suivre toute la chaîne de décision.'),t('Quel composant produit les tags de posture dans ce parcours ?',['ems','forticlient ems','forti client ems'],'EMS calcule les tags à partir des données des terminaux.'),q('Identité correcte mais posture non conforme : quel résultat attend une règle exigeant les deux ?',['Accès refusé','Accès autorisé','Changement automatique de VLAN dans tous les cas'],0,'Les deux conditions sont nécessaires dans cette règle.')]
},
{
 id:14,slug:'supervision-run',title:'Supervision et exploitation quotidienne',level:'Production',minutes:45,
 objective:'Construire une supervision qui détecte une dégradation utilement et produit une action.',prereq:'Modules 6 et 7.',
 lessons:[['Surveiller des services','La disponibilité d’une interface ne suffit pas. Surveille aussi latence, perte, CPU, mémoire, sessions, état HA, tunnels, certificats et arrivée des logs selon ton périmètre. Un test synthétique vers une application traduit mieux l’expérience utilisateur qu’un simple ping du pare-feu. Définis une référence normale avant de choisir des seuils.'],['Mesures et événements','Le polling interroge périodiquement un état ; une trap ou un événement signale une transition. Les MIB permettent à l’outil de supervision d’interpréter les objets SNMP. Préfère une configuration SNMPv3 adaptée et limite les sources de collecte. Une collecte silencieuse peut être une panne du chemin de supervision : surveille également la fraîcheur des données.'],['Organiser le RUN','Chaque alerte doit avoir gravité, destinataire, preuve à collecter et première action. Une hausse isolée de CPU ne justifie pas automatiquement un redémarrage. Corrèle-la avec charge, sessions et dégradation de service. Une procédure de changement contient état initial, modification, critères de succès, limite de temps et retour arrière. La clôture d’incident doit conserver cause et prévention.']],
 gui:'Dashboard → Status/Network ; System → SNMP selon fonctions visibles ; Log & Report pour les événements et l’arrivée des journaux.',
 cli:'get system performance status\nget system ha status\nget vpn ipsec tunnel summary',cliNote:'Lecture ponctuelle. Pour une tendance, collecte plusieurs mesures horodatées avec un outil de supervision.',
 example:'CPU à 85 % pendant quelques secondes lors d’un pic connu n’a pas le même sens que 85 % durable, sessions en hausse et application lente. Le seuil doit être lié à une durée et à un impact.',
 exercise:['Construis cinq alertes : service indisponible, tunnel, HA, ressource et absence de logs.','Pour chacune, écris seuil ou condition, durée, responsable et vérification initiale.','Simule une indisponibilité dans le laboratoire et vérifie émission, réception puis clôture de l’alerte.'],correction:'Une alerte n’est validée qu’après réception par le destinataire prévu et preuve de son retour à la normale. Le tableau de bord seul ne valide pas la chaîne d’escalade.',pitfall:'Multiplier les alertes sans durée ni propriétaire jusqu’à ce que les opérateurs cessent de les lire.',refs:['snmp','method'],
 quiz:[q('Que faut-il surveiller en plus de la valeur d’une métrique ?',['Sa fraîcheur et sa durée','Uniquement sa couleur','Le nom commercial du modèle'],0,'Une donnée figée ou un pic bref peuvent tromper.'),t('Quel protocole utilise des MIB pour les métriques réseau ?',['snmp','snmpv3','snmp v3'],'Les MIB décrivent les objets interrogeables via SNMP.'),q('Quand une alerte est-elle réellement testée ?',['Quand sa règle existe','Quand elle est reçue, comprise et se résout comme prévu','Quand le dashboard est ouvert'],1,'La chaîne de traitement doit fonctionner de bout en bout.')]
}
);
courses.push(
{
 id:15,slug:'certificats-tls',title:'Certificats et inspection TLS',level:'Production',minutes:55,
 objective:'Identifier un échec de confiance et préparer une inspection limitée à un périmètre pilote.',prereq:'Module 4 ; notions de clé publique et privée.',
 lessons:[['Vérifier une identité de service','Un certificat lie une identité à une clé publique et est signé par une autorité. Vérifie nom demandé et noms du certificat, dates, chaîne de confiance et usage prévu. Une horloge incorrecte peut rendre la validation incohérente. La clé privée doit rester protégée ; distribuer une autorité de confiance aux postes ne signifie jamais leur distribuer cette clé.'],['Deux connexions avec inspection approfondie','En deep inspection, le FortiGate termine une connexion chiffrée puis en établit une autre vers le serveur. Le client voit un certificat délivré par l’autorité utilisée pour l’inspection. Il doit lui faire confiance. L’inspection de certificat apporte une visibilité plus limitée et ne doit pas être présentée comme une analyse complète du contenu HTTPS.'],['Diagnostiquer sans élargir l’exception','Compare une connexion de référence et la connexion inspectée. Note émetteur, erreur du client et journal FortiGate. Certaines applications utilisent du pinning ou une authentification par certificat client et demandent un traitement particulier. Une exception éventuelle doit être ciblée, documentée et revue ; elle ne justifie pas de désactiver toute vérification des certificats.']],
 gui:'System → Certificates ; Security Profiles → SSL/SSH Inspection ; policy de test dans Policy & Objects.',cli:'show firewall ssl-ssh-profile\nshow firewall policy',cliNote:'Lecture des profils et de leur affectation. Ne copie pas de clés privées dans des documents de diagnostic.',
 example:'Après activation d’un profil d’inspection, seul un poste non géré affiche une autorité inconnue. Le contraste avec un poste géré oriente vers le magasin de confiance du client, à confirmer par l’émetteur affiché.',
 exercise:['Observe le certificat présenté à un poste de laboratoire avant inspection.','Sur un périmètre pilote autorisé, applique un profil et une autorité de test approuvée sur ce poste.','Compare le certificat, les journaux et le fonctionnement ; retire le profil pilote et l’autorité de test en fin d’exercice.'],correction:'Le changement d’émetteur attendu et l’absence d’erreur de confiance confirment une partie de la chaîne. Vérifie aussi que le serveur en amont reste validé et que l’application fonctionne entièrement.',pitfall:'Installer une autorité sur tous les postes avant d’avoir validé son périmètre, sa protection et les applications incompatibles.',refs:['tls'],
 quiz:[q('Le client doit-il connaître la clé privée de la CA d’inspection ?',['Oui','Non','Seulement en Wi-Fi'],1,'Il a besoin de la confiance dans le certificat CA, jamais de sa clé privée.'),t('Quel mécanisme applicatif peut rejeter un certificat substitué malgré une CA approuvée ?',['pinning','certificate pinning','certificat epingle'],'Le pinning peut imposer un certificat ou une clé attendue.'),q('Quel ensemble vérifier face à une erreur de certificat ?',['Nom, dates, chaîne et heure','Uniquement le port 443','Uniquement le routage'],0,'Ces éléments déterminent notamment la validité et la confiance.')]
},
{
 id:16,slug:'dns-dhcp-ntp',title:'Services DNS, DHCP et NTP',level:'Production',minutes:45,
 objective:'Isoler résolution de noms, attribution d’adresse et synchronisation horaire.',prereq:'Modules 2 et 6.',
 lessons:[['DHCP fournit des paramètres','Un bail associe une adresse au client pour une durée et transmet notamment passerelle et DNS. Si l’adresse est correcte mais le résolveur erroné, le poste peut joindre une IP sans joindre un nom. Un relais transporte la demande vers un serveur situé ailleurs : adresse du relais, routage et politiques du trajet font alors partie du diagnostic.'],['DNS dépend de l’émetteur','Le FortiGate résout des noms pour ses propres services ; les postes utilisent les résolveurs reçus ou configurés. Ce ne sont pas nécessairement les mêmes. Un FortiGate capable de résoudre un nom ne prouve donc pas que le poste le peut. Une réponse négative, une absence de réponse et une adresse incorrecte sont trois résultats distincts. Compare les résultats avec le résolveur réellement utilisé.'],['L’heure relie les événements','NTP permet de synchroniser les horloges ; le fuseau détermine leur affichage. Les journaux, certificats et mécanismes d’authentification deviennent difficiles à corréler avec une heure incorrecte. Contrôle source de temps, état de synchronisation et dérive. Une correction de fuseau ne répare pas nécessairement un décalage de l’horloge système.']],
 gui:'Network → DNS et Interfaces pour DNS/DHCP ; paramètres de temps système selon la version ; Dashboard → Network pour les baux.',
 cli:'show system dns\nshow system dhcp server\nshow system ntp\ndiagnose sys ntp status',cliNote:'Lecture seule. Compare la configuration aux paramètres réellement reçus sur le poste.',
 example:'Le navigateur ne trouve pas app.lab.example, mais le serveur est joignable à 10.10.20.10. Le poste interroge un résolveur qui ne connaît pas la zone interne : le test IP a isolé un problème de noms, pas validé HTTPS.',
 exercise:['Relève IP, masque, passerelle et DNS sur un poste de laboratoire.','Compare résolution d’un nom interne depuis le poste et depuis le service concerné.','Vérifie l’heure du poste, du FortiGate et du collecteur de logs ; rapproche un même événement.'],correction:'Le rapport doit distinguer paramètres DHCP, réponse DNS et synchronisation NTP. Après correction du résolveur, valide à nouveau le service par son nom et son protocole réel.',pitfall:'Remplacer tous les DNS par un résolveur public alors que les noms internes doivent être résolus par l’annuaire de l’entreprise.',refs:['dns','method'],
 quiz:[q('Une résolution réussie sur FortiGate prouve-t-elle celle du poste ?',['Oui','Non','Oui avec DHCP'],1,'Les deux peuvent utiliser des résolveurs différents.'),t('Quel protocole synchronise les horloges ?',['ntp'],'NTP synchronise l’heure ; le fuseau ne fait que modifier son affichage.'),q('Quel paramètre DHCP influence directement la résolution des noms ?',['Le serveur DNS','La couleur du port','Le numéro de série'],0,'Le résolveur fourni doit connaître les zones nécessaires.')]
},
{
 id:17,slug:'acces-distant',title:'Accès distant IPsec et authentification',level:'Production',minutes:60,
 objective:'Valider l’accès d’un utilisateur distant sans confondre tunnel, droits et application.',prereq:'Modules 5, 10 et 15.',
 lessons:[['Choisir selon la version','Dans FortiOS 7.6.3, le mode tunnel SSL VPN est remplacé par IPsec. Ne copie donc pas un guide ancien sans vérifier sa version. Distingue également Agentless VPN du tunnel réseau. Pour préparer l’accès distant, vérifie compatibilité FortiClient/FortiOS, méthode d’authentification, support MFA et contraintes réseau du poste. La version retenue ici est une référence de cours, pas une recommandation de patch de production.'],['Décrire le trajet distant','Le client doit joindre la passerelle, s’authentifier, négocier puis recevoir les paramètres adaptés. Le réseau de pool VPN ne doit pas chevaucher les réseaux nécessaires. En split tunnel, seules les destinations prévues empruntent le tunnel ; en tunnel complet, d’autres dépendances comme DNS et sortie Internet passent aussi par l’entreprise. Documente le comportement attendu avant de dépanner.'],['Autoriser au plus juste','Une connexion VPN établie ne donne pas accès à tout le LAN. Les policies doivent limiter groupes, destinations et services. Teste un utilisateur autorisé et un utilisateur hors groupe. Vérifie la résolution interne, le trajet retour et le MFA prévu. Un test positif seul ne démontre pas que les accès non autorisés sont refusés.']],
 gui:'VPN → IPsec Tunnels ; User & Authentication pour les groupes et serveurs ; Policy & Objects pour les règles d’accès.',
 cli:'get vpn ipsec tunnel summary\ndiagnose vpn tunnel list\nshow user group',cliNote:'Lecture seule. Ne publie pas les identités, secrets ou paramètres d’authentification issus des sorties.',
 example:'Le client affiche « connecté » et reçoit une adresse, mais l’application interne ne résout pas son nom. Il faut vérifier le DNS et les routes annoncées avant de recréer le tunnel.',
 exercise:['Écris une matrice utilisateur/groupe/application/service et le choix split ou full tunnel.','Dans le laboratoire, teste un compte autorisé depuis un réseau externe contrôlé.','Teste le refus d’un compte hors groupe et d’une destination non prévue, puis documente MFA, DNS et chemin retour.'],correction:'La validation combine tunnel établi, accès métier réussi et refus attendu hors périmètre. Le voyant connecté du client n’est qu’une étape.',pitfall:'Créer une policy VPN → LAN avec toutes destinations et tous services uniquement pour faire disparaître un incident.',refs:['remote','migration'],
 quiz:[q('Quel mode remplace SSL VPN tunnel à partir de FortiOS 7.6.3 ?',['IPsec VPN','Une route statique seule','DHCP'],0,'La note de version annonce le remplacement par IPsec.'),t('Comment appelle-t-on le mode où seules certaines destinations passent dans le tunnel ?',['split tunnel','split-tunnel','split tunneling'],'Le split tunnel limite les destinations routées dans le VPN.'),q('Quel test complète un accès réussi ?',['Un refus attendu hors groupe ou hors périmètre','Aucun','Seulement un test de débit'],0,'Un contrôle d’accès doit être vérifié dans les deux sens.')]
},
{
 id:18,slug:'durcissement',title:'Durcir l’administration du FortiGate',level:'Production',minutes:45,
 objective:'Réduire l’exposition administrative en gardant une voie de récupération.',prereq:'Modules 1, 3 et 15.',
 lessons:[['Identifier la surface exposée','Liste les interfaces qui acceptent HTTPS, SSH ou d’autres services de gestion et les réseaux pouvant les joindre. L’accès au pare-feu lui-même est différent du trafic transitant à travers lui. Une policy LAN → WAN ne décrit donc pas à elle seule l’exposition du plan d’administration. Préfère un réseau de gestion et des chemins d’accès maîtrisés.'],['Limiter droits et sources','Utilise des comptes nominatifs, profils d’administration adaptés et authentification renforcée lorsque prise en charge. Limite les sources de gestion avec les mécanismes appropriés, comme trusted hosts et règles local-in selon le besoin. Supprime les accès inutiles après vérification de leur usage. Le compte de secours doit être documenté et protégé, pas partagé comme compte quotidien.'],['Changer sans se verrouiller dehors','Avant toute restriction, vérifie console ou autre voie de récupération. Teste une nouvelle session autorisée avant de fermer la session courante. Valide aussi le refus depuis une source non autorisée. Les sauvegardes et secrets d’API font partie du périmètre de durcissement ; protéger le pare-feu tout en diffusant ses configurations annule une partie du bénéfice.']],
 gui:'Network → Interfaces pour les services administratifs ; System → Administrators et Admin Profiles ; local-in via les fonctions disponibles.',
 cli:'show system interface\nshow system admin\nshow firewall local-in-policy',cliNote:'Audit de lecture. La configuration des administrateurs est sensible ; ne la colle pas dans un ticket public.',
 example:'Une restriction de sources appliquée à distance utilise le mauvais sous-réseau de gestion. Sans console de secours, une action de sécurité devient une indisponibilité administrative.',
 exercise:['Inventorie services exposés, comptes et droits sur un pare-feu de laboratoire.','Prépare un accès console et limite une interface de test au poste d’administration prévu.','Ouvre une nouvelle session depuis la source autorisée, teste un refus ailleurs puis documente le retour arrière.'],correction:'La réussite exige accès permis et refus attendu, avec procédure de récupération disponible. Une session déjà ouverte qui reste active ne prouve pas qu’une nouvelle connexion sera acceptée.',pitfall:'Désactiver ou restreindre l’unique accès actif avant d’avoir testé une seconde voie.',refs:['hardening','admin','policy'],
 quiz:[q('Quand fermer la session administrative courante après une restriction ?',['Avant le test','Après validation d’une nouvelle session autorisée','Immédiatement après sauvegarde'],1,'La nouvelle session valide le chemin d’accès après changement.'),t('Quel type de policy vise le trafic destiné au FortiGate lui-même ?',['local-in','local in','local-in policy'],'Les règles local-in concernent le trafic à destination de l’équipement.'),q('Quel principe appliquer aux profils administrateurs ?',['Les droits nécessaires au rôle','Super-admin pour tous','Un seul compte partagé'],0,'Des droits adaptés limitent les effets d’une erreur ou compromission.')]
},
{
 id:19,slug:'manager-analyzer',title:'FortiManager et FortiAnalyzer en exploitation',level:'Expertise',minutes:60,
 objective:'Préparer une installation centralisée et retrouver une preuve dans les logs.',prereq:'Modules 8 et 14 ; produits de laboratoire pour les manipulations.',
 lessons:[['Définir la source de vérité','FortiManager maintient des objets et packages de policies pour des cibles de déploiement. Un changement local sur le FortiGate peut diverger de cet état. Avant d’installer, identifie la version de référence et les modifications à conserver. Les ADOM organisent des périmètres administratifs ; ils ne sont pas des VDOM réseau et ne réalisent pas le même type de séparation.'],['Prévisualiser avant d’installer','Sélectionne explicitement package et équipements cibles, vérifie les mappings d’interfaces et objets propres à chaque site, puis lis l’Install Preview. Le diff attendu doit correspondre au besoin autorisé. Une suppression inattendue est un motif de retour à l’analyse. Une installation terminée doit être suivie de tests métier et de vérification de l’état synchronisé.'],['Utiliser les journaux centralisés','FortiAnalyzer aide à explorer les événements de plusieurs équipements. Il faut vérifier réception, horodatage, périmètre de collecte et rétention. Filtre par équipement, VDOM, fenêtre temporelle et flux. Un beau rapport vide peut résulter d’un filtre inadéquat ou d’une collecte interrompue. La présence du log récent d’un test connu est une preuve plus directe.']],
 gui:'FortiManager : Device Manager et Policy & Objects → Policy Packages → Install Wizard. FortiAnalyzer : Log View et vues d’analyse selon version.',
 cli:'show system central-management\nshow log fortianalyzer setting',cliNote:'À lire sur le FortiGate pour identifier les destinations ; l’état de tâche s’examine sur FortiManager et la réception sur FortiAnalyzer.',
 example:'Le même package vise deux agences avec des noms d’interfaces différents. Sans mapping correct, le déploiement peut échouer ou ne pas représenter le chemin attendu.',
 exercise:['Crée une modification limitée dans un package de laboratoire destiné à un seul pare-feu.','Lis le diff, vérifie les cibles et installe après validation du changement prévu.','Génère une connexion de test et retrouve son journal centralisé ; compare avec le résultat métier.'],correction:'La preuve comprend le diff prévu, la tâche terminée, l’état du pare-feu et un test métier corrélé aux logs. « Install successful » ne suffit pas à valider l’application.',pitfall:'Installer un package sur tous les sites pour gagner du temps avant d’avoir vérifié les mappings et un pilote.',refs:['manager','preview','analyzer'],
 quiz:[q('À quoi sert Install Preview ?',['Vérifier les modifications avant installation','Tester le débit WAN','Créer un tunnel VPN'],0,'Il permet de confronter le diff au changement prévu.'),t('Quel domaine administratif organise les périmètres FortiManager ?',['adom','administrative domain'],'Un ADOM est un domaine administratif, distinct d’un VDOM.'),q('Un rapport vide prouve-t-il l’absence d’événements ?',['Oui','Non','Oui si le titre du rapport est correct'],1,'Collecte, filtres, heure et rétention peuvent expliquer le vide.')]
},
{
 id:20,slug:'sauvegarde-upgrade',title:'Sauvegarde, mise à jour et retour arrière',level:'Expertise',minutes:55,
 objective:'Préparer un changement FortiOS avec validation et récupération documentées.',prereq:'Modules 7, 8 et 14.',
 lessons:[['Une sauvegarde doit être restaurable','Conserve une configuration identifiée par équipement, version, date et périmètre Global/VDOM. Protège le fichier et le mot de passe de chiffrement. Une sauvegarde anonymisée destinée au partage n’est pas nécessairement suffisante pour restaurer les secrets. Vérifie l’existence et la lisibilité du fichier, puis exerce la récupération sur un environnement adapté.'],['Préparer le chemin de versions','Lis les notes de la version cible et le chemin de mise à niveau officiellement pris en charge pour le modèle et la version de départ. Certaines étapes intermédiaires sont nécessaires. Vérifie compatibilité Fabric, fonctions retirées ou modifiées et problèmes connus. Une version plus récente n’est pas automatiquement le bon choix pour toutes les productions.'],['Définir succès et échec','Avant le changement, capture état HA, tunnels, routes et tests applicatifs. Fixe une durée maximale de diagnostic avant retour arrière. Une rétrogradation peut nécessiter l’image et la configuration correspondant à la version précédente ; ne suppose pas qu’une configuration convertie sera réversible. Après mise à jour, contrôle erreurs de configuration, licences, connectivité et journaux, puis archive les preuves.']],
 gui:'Menu du compte → Configuration → Backup ; gestion du firmware dans les vues système/Fabric selon version.',
 cli:'get system status\nget system ha status\ndiagnose debug config-error-log read',cliNote:'Lecture des états et erreurs de conversion. Leur interprétation se fait avec les notes de version et la configuration de référence.',
 example:'Un équipement fournit du SSL VPN tunnel sur une version antérieure. Le passage vers 7.6.3 implique de traiter sa migration vers IPsec avant la fenêtre de changement, pas de découvrir le retrait après redémarrage.',
 exercise:['Rédige un plan pour un modèle et une version de laboratoire réellement identifiés.','Sauvegarde la configuration chiffrée, documente le chemin d’upgrade et prépare les tests avant/après.','Simule sur papier l’échec d’un service critique et décris les fichiers, accès et décisions nécessaires au retour arrière.'],correction:'Un plan complet indique point de départ exact, version cible, étapes, sauvegardes, accès de récupération, critères mesurables et personne décidant le rollback. Aucun saut de version ne doit être deviné.',pitfall:'Valider la mise à jour parce que la GUI répond, sans tester VPN, annuaire, routes, logs et applications.',refs:['backup','upgrade','migration'],
 quiz:[q('Peut-on toujours installer directement n’importe quelle version plus récente ?',['Oui','Non, il faut suivre le chemin pris en charge','Oui en HA'],1,'Le chemin dépend du modèle et de la version de départ.'),t('Quel document indique notamment les changements et problèmes connus d’une version ?',['notes de version','release notes','les notes de version'],'Les notes de version accompagnent l’analyse du chemin de mise à jour.'),q('Quel est un critère de succès suffisant ?',['La GUI répond seule','Les tests métier et états prévus sont validés','Le fichier firmware est téléchargé'],1,'La disponibilité de la GUI ne valide pas l’ensemble des services.')]
},
{
 id:21,slug:'examen-multisites',title:'Cas final : cinq incidents sur deux sites',level:'Expertise',minutes:90,
 objective:'Construire un diagnostic multi-sites, corriger des causes distinctes et justifier le résultat.',prereq:'Modules 1 à 20 ; le cas peut être travaillé sur dossier ou sur laboratoire.',
 lessons:[['Établir le périmètre','Le siège utilise 10.10.10.0/24, l’agence 10.20.10.0/24 et la DMZ 10.10.20.0/24. Le DNS interne est 10.10.20.53 ; l’application est 10.10.20.10:443. Le siège possède deux WAN et un cluster HA. Toutes ces adresses sont pédagogiques. Commence par établir les fonctions qui marchent encore pour éviter d’attribuer cinq symptômes à une cause unique sans preuve.'],['Hiérarchiser les hypothèses','Un poste sans bail, un tunnel UP sans trafic, un nom qui ne résout pas, une erreur TLS et un membre HA divergent peuvent provenir de couches différentes. Construis une matrice symptôme, hypothèse, test discriminant et résultat. Un test discriminant sépare des explications concurrentes : résolution DNS puis connexion IP, capture entrée/sortie, comparaison de certificats ou état de synchronisation.'],['Corriger et démontrer','Applique une correction limitée, répète exactement le test puis observe les effets secondaires. Conserve les états avant/après et le retour arrière. Un compte rendu final distingue faits, cause confirmée et hypothèses non vérifiées. La réussite pédagogique ne vient pas du nombre de commandes lancées : elle vient de la qualité des preuves et du maintien du périmètre d’accès.']],
 gui:'Combine Dashboard, Interfaces, Firewall Policy, IPsec, SD-WAN, HA et Log & Report selon la preuve recherchée.',
 cli:'get router info routing-table all\nget vpn ipsec tunnel summary\nget system ha status\ndiagnose sys ntp status',cliNote:'Sélectionne les commandes en fonction du symptôme. Complète si nécessaire avec les captures bornées du module 6.',
 example:'Si le DNS interne répond au siège mais pas à l’agence, commence par suivre la requête agence → 10.10.20.53 et son retour. Le service DNS globalement arrêté n’est plus l’hypothèse la plus probable.',
 exercise:['Ouvre le lab « Examen multi-sites » et rédige cinq fiches sans regarder la correction.','Pour chaque incident, donne une preuve, une correction minimale et un test de non-régression.','Compare au corrigé puis rédige un compte rendu de 15 lignes, incluant ce qui n’a pas été vérifié.'],correction:'La grille du lab final attribue quatre points par incident : localisation, preuve, correction et validation. Un accès rétabli par une règle permissive générale ne satisfait pas le critère de correction minimale.',pitfall:'Changer simultanément routes, policies et profils puis ne plus pouvoir attribuer l’amélioration à une cause précise.',refs:['method'],
 quiz:[q('Qu’est-ce qu’un test discriminant ?',['Un test qui sépare plusieurs hypothèses','Un test qui change toutes les règles','Un test de débit systématique'],0,'Il réduit l’incertitude entre des causes possibles.'),t('Après une correction, quelle étape démontre le rétablissement ?',['validation','retest','test avant apres','test de validation','valider'],'Répète le test métier et vérifie les effets secondaires.'),q('Cinq symptômes impliquent-ils forcément une cause unique ?',['Oui','Non','Oui après une mise à jour'],1,'La corrélation temporelle ne remplace pas les preuves de causalité.')]
}
);
